### ISSUE TITLE
Rework of the package system - Now called Arrows

### ISSUE THREAD

**Issue by char2cs** [rabbytesoftware/quiver#28]
# The Quiver Arrow System

Arrows are the core packages within the Quiver ecosystem. They define how dedicated servers and other applications are installed, configured, run, and managed by Quiver. Each Arrow is described by a manifest file, typically named `arrow.yaml`, which provides Quiver with all the necessary instructions and metadata.

Below is a breakdown of the `arrow.yaml` structure and its components, using the provided "Counter-Strike 2 - Template Implementation" as an example.

## 1. Arrow Manifest Version (`version`)

```yaml
version: "1.0"
```

This top-level `version` field specifies the version of the Arrow manifest schema that this particular `arrow.yaml` file adheres to. This allows Quiver to correctly parse and interpret the manifest, ensuring compatibility as the Arrow specification evolves.

## 2. Metadata (`metadata`)

The `metadata` section contains descriptive information about the Arrow.

```yaml
metadata:
  name: "Counter-Strike 2 - Template Implementation"
  description: "Counter-Strike 2 dedicated server implementation"
  mainteiners: 
    - "https://char2cs.net"
  credits:
    - "Valve Corporation"
    - "The Quiver Project && Rabbyte Software"
  license: "MIT"
  repository: "https://github.com/rabbytesoftware/arrow.cs2"
  documentation: "https://github.com/rabbytesoftware/arrow.cs2"
  version: "1.0.0"
```

*   **`name`**: A human-readable name for the Arrow (e.g., "Counter-Strike 2 Dedicated Server").
*   **`description`**: A brief summary of what the Arrow provides.
*   **`mainteiners`**: A list of individuals or organizations responsible for maintaining the Arrow. Each entry can be a name, email, or URL.
*   **`credits`**: A list acknowledging contributors, original authors, or relevant projects.
*   **`license`**: The software license under which the Arrow (and potentially the packaged software, if applicable) is distributed (e.g., "MIT", "GPL-3.0-only").
*   **`repository`**: URL to the source code repository for the Arrow manifest and related scripts.
*   **`documentation`**: URL to the Arrow's documentation.
*   **`version`**: The specific version of this Arrow package (e.g., "1.0.0", "2.1.3-beta"). This is distinct from the manifest schema version.

## 3. System Requirements (`requirements`)

This section specifies the minimum and recommended system resources for the application managed by the Arrow.

```yaml
requirements:
  minimum:
    cpu_cores: 2
    ram_gb: 4
    disk_gb: 30
    network_mbps: 10
  recommended:
    cpu_cores: 4
    ram_gb: 8
    disk_gb: 50
    network_mbps: 20
```

*   **`minimum`**: The absolute minimum resources required for the application to function.
*   **`recommended`**: The resources recommended for optimal performance.
*   **`cpu_cores`**: Number of CPU cores.
*   **`ram_gb`**: System RAM in Gigabytes.
*   **`disk_gb`**: Free disk space in Gigabytes.
*   **`network_mbps`**: Network bandwidth in Megabits per second.

Quiver can use this information to inform the user if their system meets the requirements before installation.

## 4. Dependencies (`dependencies`)

Lists other Quiver packages or tools that this Arrow relies on.

```yaml
dependencies:
  - "steamcmd" # Internally resolved by Quiver
```

Each item in the list is a dependency identifier. Quiver's package resolution system will handle fetching and making these dependencies available. For example, `steamcmd` might refer to another Arrow or a built-in tool provided by Quiver. As indicated in the example's comment, Quiver might resolve `"steamcmd"` to a specific manifest URL like `"https://raw.githubusercontent.com/rabbytesoftware/quiver.pkgs/25.05/steamcmd.yaml"`.
Properties or executable paths from these dependencies can often be referenced in the `methods` section (e.g., `${steamcmd.execute}`).

## 5. Network Bridge (`netbridge`)

Defines the network ports that the application needs to expose.

```yaml
netbridge:
  - name: "GAME_PORT"
    protocol: "tcp/udp"
```

Each item in the `netbridge` list defines a port:
*   **`name`**: A logical name for the port (e.g., "GAME_PORT", "RCON_PORT"). This name will be used as a variable (e.g., `${GAME_PORT}`) in the `methods` scripts, where Quiver will substitute it with the actual port number assigned on the host system.
*   **`protocol`**: The network protocol for the port (e.g., "tcp", "udp", "tcp/udp").

Quiver uses this information to manage port allocation, display port information to the user, and potentially assist with port forwarding.

## 6. Variables (`variables`)

Defines user-configurable parameters for the Arrow. These allow users to customize their server instance through the Quiver interface.

```yaml
variables:
  - name: "SERVER_HOSTNAME"
    default: "CS2 Server hosted with Quiver"
  - name: "DEFAULT_MAP"
    default: "de_dust2"
    values: ["de_dust2", "de_mirage", "de_inferno", "de_cache", "de_overpass", "de_nuke", "de_train", "de_vertigo", "de_ancient", "de_anubis"]
  - name: "MAX_PLAYERS"
    default: 12
    min: 2
    max: 64
  - name: "SERVER_PASSWORD"
    default: "7355608"
    sensitive: true
  - name: "RCON_PASSWORD"
    default: "7355608"
    sensitive: true
```

Each variable has:
*   **`name`**: The internal name of the variable, used for scripting (e.g., `${SERVER_HOSTNAME}`).
*   **`default`**: The default value if the user doesn't provide one.
*   **`values`** (optional): A list of predefined acceptable values, creating a dropdown/select list in the UI.
*   **`min` / `max`** (optional): For numerical values, defines the minimum and maximum allowed values.
*   **`sensitive`** (optional): If `true`, the value should be treated as sensitive (e.g., passwords) and potentially masked in UIs or logs.
*   Other potential attributes could include `description` (for UI hints), `type` (e.g., "string", "number", "boolean").

These variables are made available to the `methods` scripts.

## 7. Methods (`methods`)

This is the heart of the Arrow, defining the commands Quiver executes for various lifecycle operations. Commands can be platform-specific.

```yaml
methods:
  install:
    windows:
      - "${steamcmd.execute} +login anonymous +force_install_dir ${INSTALL_PATH} +app_update 730 validate +quit"
    linux:
      - "${steamcmd.execute} +login anonymous +force_install_dir ${INSTALL_PATH} +app_update 730 validate +quit"
  execute:
    windows:
      - "${INSTALL_PATH}\\cs2.exe -dedicated -console -usercon +hostname ${SERVER_HOSTNAME} +map ${DEFAULT_MAP} +maxplayers ${MAX_PLAYERS} +sv_password ${SERVER_PASSWORD} -port ${GAME_PORT}"
    linux:
      - "${INSTALL_PATH}/cs2 -dedicated -console -usercon +hostname ${SERVER_HOSTNAME} +map ${DEFAULT_MAP} +maxplayers ${MAX_PLAYERS} +sv_password ${SERVER_PASSWORD} -port ${GAME_PORT}"
  uninstall:
    # ...
  update:
    # ...
  validate:
    # ...
```

*   **Standard Methods**:
    *   **`install`**: Commands to download, set up, and install the application.
    *   **`execute`** (or `run`): Commands to start the application.
    *   **`uninstall`**: Commands to remove the application and clean up.
    *   **`stop`** (not shown in example, but typical): Commands to gracefully stop the application. Quiver might have a default way to stop processes if not specified.
*   **Custom/Optional Methods**:
    *   **`update`**: Commands to update the application.
    *   **`validate`**: Commands to verify the integrity of the installation.
*   **Platform Specificity**: Commands can be defined for `windows`, `linux`, and `macos`. Quiver will execute the appropriate commands based on the user's operating system.
*   **Scripting**:
    *   Each method contains a list of command strings to be executed sequentially.
    *   **Variable Interpolation**: Quiver substitutes placeholders like `${VARIABLE_NAME}` with their actual values at runtime. This includes:
        *   User-defined variables from the `variables` section (e.g., `${SERVER_HOSTNAME}`).
        *   Quiver-provided variables (e.g., `${INSTALL_PATH}` which is the directory where the Arrow's application files are stored, `${GAME_PORT}` which is the actual port number assigned by Quiver).
        *   Variables from dependencies (e.g., `${steamcmd.execute}` which might resolve to the path of the steamcmd executable).

## How Quiver Uses This Information

1.  **Discovery & Display**: Quiver uses `metadata` to list and describe Arrows to users.
2.  **Pre-flight Checks**: `requirements` help inform users if their system is suitable.
3.  **Dependency Management**: Quiver resolves and installs items listed in `dependencies`.
4.  **Configuration**: Quiver's UI presents `variables` to the user for customization. These values are then injected into the method scripts.
5.  **Network Setup**: `netbridge` information is used to allocate ports and potentially guide users through port forwarding.
6.  **Lifecycle Management**: Quiver executes the commands defined in `methods` when a user performs actions like "Install," "Run," "Stop," or "Uninstall" via the Quiver interface.
